# BSD 2-Clause License
#
# Copyright (c) 2026, Renaud Allard <renaud@allard.it>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


"""Regenerate the content type table from the schema the descriptions name.

    python tools/make_content_types.py

Every appliance description includes two definition files by their address on
the Home Connect schema host, and says so in its own opening lines:

    <xi:include href=".../HC_INT_BSH_CTD.xml" parse="xml"/>

A description gives each numbered thing a `refCID`, and that file is what the
number means: `0010` is a length of time in seconds, `0005` is a string whose
bounds are how long it may be rather than how large it may be. Without it a
description says how big a thing may be and never what it is.

The table is generated rather than fetched while running. An integration
should not have to reach a schema host to name a unit, and this file has been
at the same address since 2014 and is what current appliances still point at.
"""

from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

WHERE = "https://www.home-connect.com/schemas/DeviceDescription/20140417"
CTD = f"{WHERE}/HC_INT_BSH_CTD.xml"

MINE = Path(__file__)
WRITTEN = Path("custom_components/homeconnect/content.py")

# What the generated module says for itself, the licence above it being the
# same one this file carries and taken from here rather than written twice.
PREAMBLE = '''
"""What the number on a described thing says it is.

Generated by tools/make_content_types.py from the schema every appliance
description includes by its address:

    {where}

Do not edit this file: run the tool.

A description gives each numbered thing a refCID. That says what the thing is,
where the description itself says only how large it may be, so it is what
tells a length of time from a plain figure, and a string whose bounds are its
length from a number whose bounds are its range.
"""

from __future__ import annotations

# How a value travels, which is what says whether bounds are a range or a
# length, and whether there is a single value at all.
BOOLEAN = "Boolean"
INTEGER = "Integer"
FLOAT = "Float"
STRING = "String"
OBJECT = "Object"

# By the number a description writes, as what it is and how it is carried.
CONTENT: dict[int, tuple[str, str]] = {{
{rows}
}}


def content(number: int | None) -> tuple[str, str] | None:
    """What a refCID says a thing is, or nothing for one nobody published."""
    return CONTENT.get(number) if number is not None else None
'''


def fetched(url: str) -> str:
    with urllib.request.urlopen(url, timeout=30) as answer:
        return str(answer.read().decode("utf-8"))


def types(xml: str) -> list[tuple[int, str, str]]:
    """Every content type, as its number, what it is and how it is carried."""
    found = []
    for attrs in re.findall(r"<contentType\b([^>]*?)/?>", xml):
        number = re.search(r'cid="([0-9a-fA-F]+)"', attrs)
        named = re.search(r'\btype="([^"]*)"', attrs)
        carried = re.search(r'protocolType="([^"]*)"', attrs)
        if number and named and carried:
            found.append((int(number.group(1), 16), named.group(1), carried.group(1)))
    return sorted(found)


def main() -> int:
    found = types(fetched(CTD))
    if not found:
        print(f"{CTD} named no content types", file=sys.stderr)
        return 1
    rows = "\n".join(
        f'    0x{number:04X}: ("{named}", {carried.upper()}),'
        for number, named, carried in found
    )
    licence = "".join(MINE.read_text().splitlines(keepends=True)[:26])
    WRITTEN.write_text(licence + PREAMBLE.format(where=CTD, rows=rows))
    print(f"wrote {len(found)} content types to {WRITTEN}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
