# BSD 2-Clause License
#
# Copyright (c) 2026, Renaud Allard <renaud@allard.it>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


"""What the number on a described thing says it is.

Generated by tools/make_content_types.py from the schema every appliance
description includes by its address:

    https://www.home-connect.com/schemas/DeviceDescription/20140417/HC_INT_BSH_CTD.xml

Do not edit this file: run the tool.

A description gives each numbered thing a refCID. That says what the thing is,
where the description itself says only how large it may be, so it is what
tells a length of time from a plain figure, and a string whose bounds are its
length from a number whose bounds are its range.
"""

from __future__ import annotations

# How a value travels, which is what says whether bounds are a range or a
# length, and whether there is a single value at all.
BOOLEAN = "Boolean"
INTEGER = "Integer"
FLOAT = "Float"
STRING = "String"
OBJECT = "Object"

# By the number a description writes, as what it is and how it is carried.
CONTENT: dict[int, tuple[str, str]] = {
    0x0001: ("boolean", BOOLEAN),
    0x0002: ("integer", INTEGER),
    0x0003: ("enumeration", INTEGER),
    0x0004: ("float", FLOAT),
    0x0005: ("string", STRING),
    0x0006: ("dateTime", STRING),
    0x0007: ("temperatureCelsius", FLOAT),
    0x0008: ("temperatureFahrenheit", FLOAT),
    0x000A: ("hexBinary", STRING),
    0x0010: ("timeSpan", INTEGER),
    0x0011: ("percent", FLOAT),
    0x0012: ("dbm", INTEGER),
    0x0013: ("weight", INTEGER),
    0x0014: ("liquidVolume", INTEGER),
    0x0015: ("uidValue", INTEGER),
    0x0016: ("date", STRING),
    0x0017: ("time", STRING),
    0x0018: ("waterHardness", INTEGER),
    0x0019: ("point2D", OBJECT),
    0x001A: ("pose2D", OBJECT),
    0x001B: ("line2D", OBJECT),
    0x001E: ("rgb", STRING),
    0x001F: ("rpm", INTEGER),
    0x0020: ("flowRate", INTEGER),
    0x0021: ("length", FLOAT),
    0x0022: ("area", FLOAT),
    0x0023: ("power", FLOAT),
    0x0024: ("energy", FLOAT),
    0x0025: ("bigInteger", INTEGER),
    0x0026: ("identifier", INTEGER),
    0x0027: ("speed", FLOAT),
    0x0028: ("programInstruction", OBJECT),
    0x0029: ("weightPound", FLOAT),
    0x002A: ("localeString", OBJECT),
    0x002B: ("teaspoon", FLOAT),
    0x002C: ("tablespoon", FLOAT),
    0x002D: ("cup", FLOAT),
    0x002E: ("piece", FLOAT),
    0x002F: ("byteLength", INTEGER),
    0x0030: ("uuid", STRING),
    0x0031: ("timezone", OBJECT),
    0x0032: ("csv", STRING),
    0x0033: ("leaf", FLOAT),
    0x0034: ("bunch", FLOAT),
    0x0035: ("casket", FLOAT),
    0x0036: ("pinch", FLOAT),
    0x0037: ("stalk", FLOAT),
    0x0038: ("stick", FLOAT),
    0x0039: ("branch", FLOAT),
    0x003A: ("tray", INTEGER),
    0x003B: ("portion", INTEGER),
    0x003C: ("genericJson", OBJECT),
    0x003D: ("utcDateTime", STRING),
    0x003E: ("programRunSummary", OBJECT),
    0x003F: ("programSessionSummary", OBJECT),
    0x0040: ("liquidVolumeThroughput", FLOAT),
    0x0041: ("weightOunces", FLOAT),
    0x0042: ("rectangle2D", OBJECT),
    0x0081: ("booleanList", OBJECT),
    0x0082: ("integerList", OBJECT),
    0x0083: ("enumerationList", OBJECT),
    0x0084: ("floatList", OBJECT),
    0x0085: ("stringList", OBJECT),
    0x0086: ("dateTimeList", OBJECT),
    0x0087: ("temperatureCelsiusList", OBJECT),
    0x0088: ("temperatureFahrenheitList", OBJECT),
    0x008A: ("hexBinaryList", OBJECT),
    0x0090: ("timeSpanList", OBJECT),
    0x0091: ("percentList", OBJECT),
    0x0092: ("dBmList", OBJECT),
    0x0093: ("weightList", OBJECT),
    0x0094: ("liquidVolumeList", OBJECT),
    0x0095: ("uidValueList", OBJECT),
    0x0096: ("dateList", OBJECT),
    0x0097: ("timeList", OBJECT),
    0x0098: ("waterHardnessList", OBJECT),
    0x0099: ("point2DList", OBJECT),
    0x009A: ("pose2DList", OBJECT),
    0x009B: ("line2DList", OBJECT),
    0x009C: ("path", OBJECT),
    0x009D: ("polygon", OBJECT),
    0x009E: ("rgbList", OBJECT),
    0x009F: ("rpmList", OBJECT),
    0x00A0: ("flowRateList", OBJECT),
    0x00A1: ("lengthList", OBJECT),
    0x00A2: ("areaList", OBJECT),
    0x00A3: ("powerList", OBJECT),
    0x00A4: ("energyList", OBJECT),
    0x00A5: ("bigIntegerList", OBJECT),
    0x00A6: ("identifierList", OBJECT),
    0x00A7: ("speedList", OBJECT),
    0x00A8: ("programInstructionList", OBJECT),
    0x00A9: ("weightPoundList", OBJECT),
    0x00AA: ("localeStringList", OBJECT),
    0x00AB: ("teaspoonList", OBJECT),
    0x00AC: ("tablespoonList", OBJECT),
    0x00AD: ("cupList", OBJECT),
    0x00AE: ("pieceList", OBJECT),
    0x00AF: ("byteLengthList", OBJECT),
    0x00B0: ("uuidList", OBJECT),
    0x00B1: ("timezoneList", OBJECT),
    0x00B2: ("csvList", OBJECT),
    0x00B3: ("leafList", OBJECT),
    0x00B4: ("bunchList", OBJECT),
    0x00B5: ("casketList", OBJECT),
    0x00B6: ("pinchList", OBJECT),
    0x00B7: ("stalkList", OBJECT),
    0x00B8: ("stickList", OBJECT),
    0x00B9: ("branchList", OBJECT),
    0x00BA: ("trayList", OBJECT),
    0x00BB: ("portionList", OBJECT),
    0x00BC: ("genericJsonList", OBJECT),
    0x00BD: ("utcDateTimeList", OBJECT),
    0x00BE: ("programRunSummaryList", OBJECT),
    0x00BF: ("programSessionSummaryList", OBJECT),
    0x00C0: ("liquidVolumeThroughputList", OBJECT),
    0x00C1: ("weightOuncesList", OBJECT),
    0x00C2: ("rectangle2DList", OBJECT),
}


def content(number: int | None) -> tuple[str, str] | None:
    """What a refCID says a thing is, or nothing for one nobody published."""
    return CONTENT.get(number) if number is not None else None
